# Generated by Django 6.0.1 on 2026-01-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('attachment', 'Attachment'), ('intern', 'Internship'), ('entry', 'Entry Level'), ('junior', 'Junior'), ('grad', 'Graduate Trainee')], default='entry', max_length=20),
        ),
    ]
